const shopTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_END: "FETCH_COLLECTION_END",
  FETCH_COLLECTION_ERROR: "FETCH_COLLECTION_ERROR"
};

export default shopTypes;